fint:
  security:
    component: false
    org-id: false
    scope: false

spring:
  threads:
    virtual:
      enabled: true

logging:
  level:
    notprivacysafe.graphql.GraphQL: ERROR
    no.fintlabs: DEBUG