apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-graphql
  namespace: fint-core
spec:
  imagePullPolicy: Always
  orgId: fint-core
  image: ghcr.io/fintlabs/fint-core-graphql:latest
  env:
    - name: fint.graphql.baseurl
      value: beta.felleskomponent.no
  url:
    hostname: beta.felleskomponent.no
    basePath: /core/graphql
  ingress:
    enabled: true
  resources:
    limits:
      memory: "512Mi"
      cpu: "1"
    requests:
      memory: "256Mi"
      cpu: "250m"